export enum OrderStatusEnum {
  CREATED = 'CREATED',
  RESTAURANT_VALIDATED = 'RESTAURANT_VALIDATED',
  PREPARING = 'PREPARING',
  DELIVERER_ACCEPTED = 'DELIVERER_ACCEPTED',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
